### ISSUE TITLE
Seqmentation fault in inchi-1.exe  with /InChI2InChI validation

### ISSUE THREAD

**Issue by baleland** [IUPAC-InChI/InChI#28] opened 2024-07-18 19:06 UTC
```
CMD> inchi-1.exe INPUT_10_inchi.txt /InChI2InChI
InChI version 1, Software v. 1.07 (inchi-1 executable)
Windows 64-bit Build (MS VS 2017 or later) of Jul 16 2024 16:25:04

Opened log file 'INPUT_10.inchi.log'
Opened input file 'INPUT_10.inchi'
Opened output file 'INPUT_10.inchi.txt'
Opened problem file 'INPUT_10.inchi.prb'
The command line used:
".\InChI_1_07_0\inchi-1.exe INPUT_10.inchi /InChI2InChI"
Generating standard InChI
Input format: InChI (plain identifier)
Output format: Plain text
Aux. info suppressed
Timeout per structure: 60000 msec
Up to 1024 atoms per structure



Structure: 8 Syntax error (-2) in FIXED_H (18)
**CRASH**
```

though with JUST the 2 problem records & no prior parsing, the run succeeds,

```
CMD> inchi-1.exe INPUT_LAST_2_inchi.txt /InChI2InChI
InChI version 1, Software v. 1.07 (inchi-1 executable)
Windows 64-bit Build (MS VS 2017 or later) of Jul 16 2024 16:25:04

Opened log file 'INPUT_LAST_2.inchi.log'
Opened input file 'INPUT_LAST_2.inchi'
Opened output file 'INPUT_LAST_2.inchi.txt'
Opened problem file 'INPUT_LAST_2.inchi.prb'
The command line used:
".\InChI_1_07_0\inchi-1.exe INPUT_LAST_2.inchi /InChI2InChI"
Generating standard InChI
Input format: InChI (plain identifier)
Output format: Plain text
Aux. info suppressed
Timeout per structure: 60000 msec
Up to 1024 atoms per structure



Structure: 1 Syntax error (-2) in FIXED_H (18)

Structure: 2 Syntax error (-2) in FIXED_H (18)
Finished processing 2 structures: 0 errors, processing time 0:00:00.00

Elapsed walltime: 16 msec.
```

[INPUT_LAST_2_inchi.txt](https://github.com/user-attachments/files/16287987/INPUT_LAST_2_inchi.txt)
[INPUT_10_inchi.txt](https://github.com/user-attachments/files/16287988/INPUT_10_inchi.txt)

**Comment by djb-rwth** [comment] 2024-07-19 16:18
Duplicate of #27

**Comment by baleland** [comment] 2024-07-19 16:30
maybe the crash is just a manifestation of the syntax error, but doesn't seem like a "duplicate"

**Closed** 2024-08-13 17:36 UTC
Labels: bug
